In [61]:
# librays
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv("../data/raw/purplle_campaign_data_with_nulls.csv")
df2 = pd.read_csv("../data/raw/nykaa_campaign_data_with_nulls.csv")
df3 = pd.read_csv("../data/raw/tira_campaign_data_with_nulls.csv")

In [4]:
df1.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,PU-CMP-1000,Paid Ads,Working Women,6.0,"Facebook, Google",31869.0,3490.0,1946.0,902.0,493394.0,55.93,8.78,Tamil,19.89,Premium Shoppers,27-12-2024
1,PU-CMP-1001,Paid Ads,Premium Shoppers,8.0,"Instagram, WhatsApp",26640.0,2441.0,741.0,314.0,108644.0,197.44,0.75,Bengali,13.12,NaN,26-11-2024
2,PU-CMP-1002,Influencer,Youth,22.0,"Facebook, WhatsApp",36967.0,4997.0,1025.0,653.0,NaN,234.59,0.56,NaN,18.06,College Students,08-01-2025
3,PU-CMP-1003,Paid Ads,Youth,15.0,"Instagram, WhatsApp",73258.0,5893.0,2565.0,1970.0,1341570.0,103.76,5.56,Bengali,14.23,College Students,14-03-2025
4,PU-CMP-1004,Social Media,Premium Shoppers,11.0,"WhatsApp, Instagram",91081.0,6393.0,3282.0,2582.0,787510.0,78.61,NaN,English,13.46,College Students,11-07-2024

In [5]:
df2.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [6]:
df3.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.72,0.80,Tamil,NaN,Premium Shoppers,30-10-2024
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.36,1.46,Tamil,3.98,College Students,11-09-2024
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,NaN,2.62,English,8.58,Tier 2 City Customers,28-08-2024
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.0,3721.0,2088.0,736.0,571872.0,161.13,3.82,Bengali,20.76,Youth,27-07-2024
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.0,7277.0,3615.0,2602.0,1477936.0,82.07,NaN,Tamil,21.96,College Students,19-12-2024

In [14]:
df1.columns.tolist()

['Campaign_ID',
 'Campaign_Type',
 'Target_Audience',
 'Duration',
 'Channel_Used',
 'Impressions',
 'Clicks',
 'Leads',
 'Conversions',
 'Revenue',
 'Acquisition_Cost',
 'ROI',
 'Language',
 'Engagement_Score',
 'Customer_Segment',
 'Date']

In [21]:
print(df1["Campaign_Type"].unique())
print(df1["Target_Audience"].unique())

<ArrowStringArray>
['Paid Ads', 'Influencer', 'Social Media', 'SEO', nan, 'Email']
Length: 6, dtype: str
<ArrowStringArray>
[        'Working Women',      'Premium Shoppers',                 'Youth',
 'Tier 2 City Customers',      'College Students',                     nan]
Length: 6, dtype: str

In [22]:
print(df2["Campaign_Type"].unique())
print(df2["Target_Audience"].unique())

<ArrowStringArray>
['Social Media', 'Paid Ads', 'Influencer', 'Email', nan, 'SEO']
Length: 6, dtype: str
<ArrowStringArray>
[     'College Students', 'Tier 2 City Customers',                 'Youth',
         'Working Women',      'Premium Shoppers',                     nan]
Length: 6, dtype: str

In [23]:
print(df3["Campaign_Type"].unique())
print(df3["Target_Audience"].unique())

<ArrowStringArray>
['SEO', 'Social Media', nan, 'Email', 'Paid Ads', 'Influencer']
Length: 6, dtype: str
<ArrowStringArray>
[        'Working Women', 'Tier 2 City Customers',                 'Youth',
      'Premium Shoppers',      'College Students',                     nan]
Length: 6, dtype: str

In [33]:
print(df1["Customer_Segment"].unique())

<ArrowStringArray>
[     'Premium Shoppers',                     nan,      'College Students',
         'Working Women', 'Tier 2 City Customers',                 'Youth']
Length: 6, dtype: str

In [31]:
all_channels = df1['Channel_Used'].dropna().str.split(',').explode(ignore_index= True).str.strip()

unique_channels = all_channels.unique()
print(unique_channels)

<ArrowStringArray>
['Facebook', 'Google', 'Instagram', 'WhatsApp', 'Email', 'YouTube']
Length: 6, dtype: str

In [57]:
df1["Language"].unique()

<ArrowStringArray>
['Tamil', 'Bengali', nan, 'English', 'Hindi']
Length: 5, dtype: str

In [58]:
df2["Language"].unique()

<ArrowStringArray>
['Hindi', 'English', nan, 'Tamil', 'Bengali']
Length: 5, dtype: str

looks like each dataset have same unique channels, unique audience, customer segment, campaign type, target audience

In [37]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       52871 non-null  str
 1   Campaign_Type     52765 non-null  str
 2   Target_Audience   52808 non-null  str
 3   Duration          52787 non-null  float64
 4   Channel_Used      52811 non-null  str
 5   Impressions       52834 non-null  float64
 6   Clicks            52843 non-null  float64
 7   Leads             52901 non-null  float64
 8   Conversions       52881 non-null  float64
 9   Revenue           52792 non-null  float64
 10  Acquisition_Cost  52857 non-null  float64
 11  ROI               52824 non-null  float64
 12  Language          52810 non-null  str
 13  Engagement_Score  52953 non-null  float64
 14  Customer_Segment  52879 non-null  str
 15  Date              52904 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

In [38]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  str
 1   Campaign_Type     52696 non-null  str
 2   Target_Audience   52794 non-null  str
 3   Duration          52665 non-null  float64
 4   Channel_Used      52750 non-null  str
 5   Impressions       52775 non-null  float64
 6   Clicks            52773 non-null  float64
 7   Leads             52776 non-null  float64
 8   Conversions       52889 non-null  float64
 9   Revenue           52743 non-null  float64
 10  Acquisition_Cost  52742 non-null  float64
 11  ROI               52730 non-null  float64
 12  Language          52787 non-null  str
 13  Engagement_Score  52806 non-null  float64
 14  Customer_Segment  52767 non-null  str
 15  Date              52797 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

In [39]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       52822 non-null  str
 1   Campaign_Type     52846 non-null  str
 2   Target_Audience   52891 non-null  str
 3   Duration          52890 non-null  float64
 4   Channel_Used      52822 non-null  str
 5   Impressions       52832 non-null  float64
 6   Clicks            52825 non-null  float64
 7   Leads             52898 non-null  float64
 8   Conversions       52895 non-null  float64
 9   Revenue           52826 non-null  float64
 10  Acquisition_Cost  52905 non-null  float64
 11  ROI               52813 non-null  float64
 12  Language          52769 non-null  str
 13  Engagement_Score  52825 non-null  float64
 14  Customer_Segment  52844 non-null  str
 15  Date              52865 non-null  str
dtypes: float64(9), str(7)
memory usage: 10.9 MB

In [45]:
df1.isnull().sum()

Campaign_ID         2684
Campaign_Type       2790
Target_Audience     2747
Duration            2768
Channel_Used        2744
Impressions         2721
Clicks              2712
Leads               2654
Conversions         2674
Revenue             2763
Acquisition_Cost    2698
ROI                 2731
Language            2745
Engagement_Score    2602
Customer_Segment    2676
Date                2651
dtype: int64

In [48]:
df1.isnull().mean() * 100

Campaign_ID         4.831248
Campaign_Type       5.022050
Target_Audience     4.944649
Duration            4.982450
Channel_Used        4.939249
Impressions         4.897849
Clicks              4.881649
Leads               4.777248
Conversions         4.813248
Revenue             4.973450
Acquisition_Cost    4.856449
ROI                 4.915849
Language            4.941049
Engagement_Score    4.683647
Customer_Segment    4.816848
Date                4.771848
dtype: float64

In [49]:
df2.isnull().sum()

Campaign_ID            0
Campaign_Type       2859
Target_Audience     2761
Duration            2890
Channel_Used        2805
Impressions         2780
Clicks              2782
Leads               2779
Conversions         2666
Revenue             2812
Acquisition_Cost    2813
ROI                 2825
Language            2768
Engagement_Score    2749
Customer_Segment    2788
Date                2758
dtype: int64

In [50]:
df3.isnull().sum()

Campaign_ID         2733
Campaign_Type       2709
Target_Audience     2664
Duration            2665
Channel_Used        2733
Impressions         2723
Clicks              2730
Leads               2657
Conversions         2660
Revenue             2729
Acquisition_Cost    2650
ROI                 2742
Language            2786
Engagement_Score    2730
Customer_Segment    2711
Date                2690
dtype: int64

In [54]:
print(df1.duplicated().sum())
print(df1['Campaign_ID'].dropna().duplicated().sum())

0
0

In [55]:
print(df2.duplicated().sum())
print(df2['Campaign_ID'].dropna().duplicated().sum())

0
0

In [56]:
print(df3.duplicated().sum())
print(df3['Campaign_ID'].dropna().duplicated().sum())

0
0

In [60]:
df1.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,52787.000000,52834.000000,52843.000000,52901.000000,52881.000000,5.279200e+04,52857.000000,52824.000000,52953.000000
mean,17.487279,55081.247398,4682.958973,1873.141907,1027.354324,5.135680e+05,377.986979,2.681688,13.756857
std,7.492281,25955.720822,3179.537407,1432.215726,857.583756,4.876494e+05,536.908374,4.474675,6.334863
min,5.000000,10001.000000,207.000000,48.000000,19.000000,6.061000e+03,9.340000,-0.970000,2.560000
25%,11.000000,32658.500000,2111.000000,781.000000,399.000000,1.770750e+05,107.380000,0.040000,8.340000
50%,17.000000,55134.000000,3901.000000,1474.000000,772.000000,3.578840e+05,210.120000,1.220000,13.570000
75%,24.000000,77700.000000,6705.500000,2597.000000,1402.000000,6.867660e+05,431.880000,3.550000,18.790000
max,30.000000,100000.000000,14888.000000,8613.000000,6221.000000,4.345920e+06,12109.050000,66.840000,30.990000

In [63]:
df2.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,52665.000000,52775.000000,52773.000000,52776.000000,52889.000000,5.274300e+04,52742.000000,52730.000000,52806.000000
mean,17.444508,55119.386698,4690.636879,1876.938684,1033.357239,5.156704e+05,377.587214,2.718973,13.781463
std,7.515052,25913.116620,3178.575040,1435.723927,863.080820,4.900234e+05,542.150864,4.492699,6.351002
min,5.000000,10001.000000,202.000000,56.000000,20.000000,6.183000e+03,9.430000,-0.970000,2.600000
25%,11.000000,32748.000000,2113.000000,778.000000,400.000000,1.773790e+05,105.150000,0.040000,8.360000
50%,17.000000,55189.000000,3909.000000,1479.000000,778.000000,3.598320e+05,207.230000,1.250000,13.610000
75%,24.000000,77535.500000,6697.000000,2606.000000,1415.000000,6.881200e+05,428.500000,3.630000,18.850000
max,30.000000,100000.000000,14868.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,74.420000,30.910000

In [64]:
df3.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,52890.000000,52832.000000,52825.000000,52898.000000,52895.000000,5.282600e+04,52905.000000,52813.000000,52825.000000
mean,17.533768,55005.698421,4681.332343,1866.431831,1024.783325,5.122444e+05,374.920868,2.687977,13.756235
std,7.497857,26016.433598,3174.005400,1422.867526,852.359561,4.851018e+05,531.010003,4.488936,6.298586
min,5.000000,10001.000000,208.000000,50.000000,17.000000,3.895000e+03,8.180000,-0.990000,2.580000
25%,11.000000,32426.000000,2108.000000,778.000000,402.000000,1.780650e+05,107.480000,0.060000,8.430000
50%,18.000000,54980.000000,3912.000000,1475.000000,775.000000,3.590540e+05,208.710000,1.240000,13.570000
75%,24.000000,77513.250000,6681.000000,2596.750000,1391.000000,6.822630e+05,425.880000,3.560000,18.720000
max,30.000000,99999.000000,14944.000000,8761.000000,6415.000000,4.517478e+06,15038.000000,79.300000,30.520000

In [ ]:
expected_roi = (df1['Revenue'] - df1['Acquisition_Cost']) / df1['Acquisition_Cost']
errors = (df1['ROI'] - expected_roi).abs()
errors.describe()

count     47783.000000
mean       6388.637092
std       14216.207753
min           0.761219
25%         437.235517
50%        1747.538231
75%        6095.290174
max      347008.436276
dtype: float64

In [73]:
print((errors > 0.1).sum())      
print((errors > 0.1).mean() * 100)

47783
86.01026010260102

In [79]:
df1.isnull().sum(axis=1).value_counts().sort_index()

0    24901
1    20578
2     7840
3     1890
4      304
5       37
6        4
7        1
Name: count, dtype: int64

In [80]:
(df1.isnull().sum(axis=1) > 0).mean() * 100

np.float64(55.177751777517784)

In [81]:
(df1.isnull().sum(axis=1) >= 2).mean() * 100

np.float64(18.136981369813697)

In [82]:
df2.isnull().sum(axis=1).value_counts().sort_index()

0    25657
1    20336
2     7535
3     1717
4      274
5       34
6        2
Name: count, dtype: int64

In [83]:
(df2.isnull().sum(axis=1) > 0).mean() * 100

np.float64(53.816938169381686)

In [85]:
df3.isnull().sum(axis=1).value_counts().sort_index()

0    25003
1    20432
2     7903
3     1839
4      339
5       34
6        4
7        1
Name: count, dtype: int64

In [84]:
(df3.isnull().sum(axis=1) > 0).mean() * 100

np.float64(54.994149941499415)